import Link from "next/link";
import { cookies } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { FiArrowLeft, FiArrowUpRight, FiArrowDownRight } from "react-icons/fi";
import { requireAuthToken } from "@/lib/auth";
import { loadHolding } from "@/lib/holding-position";
import { HOLDING_AGENTS } from "@/lib/holding-insight";
import HoldingInsightPanel from "@/components/portfolio/holding-insight-panel";
import TradeButtons from "@/components/trading/trade-buttons";

export const dynamic = "force-dynamic";

/**
 * One holding, in detail.
 *
 * The portfolio table can only show a row's worth of a position. This is the
 * page behind that row: the numbers in full, every fill that built the
 * position, and three agents asked about this specific holding rather than
 * about the stock in the abstract.
 */

const inr = (n: number, max = 2) =>
  `₹${n.toLocaleString("en-IN", { minimumFractionDigits: max, maximumFractionDigits: max })}`;

const PRICE_SOURCE_NOTE: Record<string, string> = {
  live: "Live price",
  delayed: "Delayed price (Yahoo) — the live market feed is unavailable",
  "last-trade": "No market price available — showing your last fill",
};

export default async function HoldingDetailPage({
  params,
}: {
  params: { symbol: string };
}) {
  const token = cookies().get("access_token")?.value ?? null;
  const auth = await requireAuthToken(token);
  if (!auth) redirect("/login");

  /*
   * This page is mounted under both /user/portfolio and /advisor/portfolio.
   * The back link has to follow the role, because app/user/layout.tsx bounces
   * advisors out of /user/* — sending one "back to Portfolio" would land them
   * on their own dashboard instead.
   */
  const backHref = auth.role === "advisor" ? "/advisor/paper" : "/user/portfolio";

  const symbol = decodeURIComponent(params.symbol).toUpperCase();
  const holding = await loadHolding(auth.userId, symbol);
  // Not a 404 for "no such stock" — a 404 for "you do not hold this", which is
  // the only way to reach this page by mistake.
  if (!holding) notFound();

  const { context: h, trades, priceSource } = holding;
  const up = h.unrealizedPnL >= 0;

  const stats = [
    { label: "Quantity", value: h.quantity.toLocaleString("en-IN") },
    { label: "Average cost", value: inr(h.avgPrice) },
    { label: "Current price", value: inr(h.lastPrice) },
    { label: "Position value", value: inr(h.marketValue) },
    { label: "Invested", value: inr(h.avgPrice * h.quantity) },
    { label: "Portfolio weight", value: `${h.weightPct.toFixed(1)}%` },
  ];

  return (
    <section className="hd-page">
      <Link href={backHref} className="hd-back">
        <FiArrowLeft size={14} /> Back to Portfolio
      </Link>

      <header className="hd-head">
        <div className="hd-head-id">
          <h1 className="hd-symbol">{h.symbol}</h1>
          <p className="hd-sub">
            {h.heldDays == null
              ? "Paper position"
              : h.heldDays === 0
                ? "Opened today · paper position"
                : `Held ${h.heldDays} day${h.heldDays === 1 ? "" : "s"} · paper position`}
          </p>
        </div>

        <div className="hd-head-price">
          <div className="hd-ltp">{inr(h.lastPrice)}</div>
          <div className={`hd-pnl ${up ? "up" : "down"}`}>
            {up ? <FiArrowUpRight size={14} /> : <FiArrowDownRight size={14} />}
            {up ? "+" : ""}
            {inr(h.unrealizedPnL)} ({up ? "+" : ""}
            {h.unrealizedPnLPct.toFixed(2)}%)
          </div>
          <div className="hd-price-note">{PRICE_SOURCE_NOTE[priceSource]}</div>
        </div>

        <div className="hd-head-actions">
          <TradeButtons
            symbol={h.symbol}
            instrumentType="EQ"
            exchange="NSE"
            price={h.lastPrice}
            size="md"
          />
        </div>
      </header>

      <div className="hd-stats">
        {stats.map((s) => (
          <div key={s.label} className="hd-stat">
            <span className="hd-stat-label">{s.label}</span>
            <strong className="hd-stat-value">{s.value}</strong>
          </div>
        ))}
      </div>

      {/* ── AI reads ─────────────────────────────────────────────────────── */}
      <div className="hd-section-head">
        <h2>What the agents make of it</h2>
        <p>
          Each of these is asked about <strong>your</strong> position — your size,
          your average cost, and the rest of your portfolio — not about {h.symbol}{" "}
          in the abstract. Generated by AI; not investment advice.
        </p>
      </div>

      <div className="hd-insights">
        {HOLDING_AGENTS.map((a) => (
          <HoldingInsightPanel
            key={a.key}
            symbol={h.symbol}
            agentKey={a.key}
            label={a.label}
            blurb={a.blurb}
            icon={a.icon}
          />
        ))}
      </div>

      {/* ── Fills ────────────────────────────────────────────────────────── */}
      <div className="hd-section-head">
        <h2>Your trades in {h.symbol}</h2>
        <p>Every fill that built this position, newest first.</p>
      </div>

      <article className="hd-card">
        <div className="hd-table-wrap">
          <table className="hd-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Side</th>
                <th className="num">Quantity</th>
                <th className="num">Price</th>
                <th className="num">Value</th>
              </tr>
            </thead>
            <tbody>
              {trades.map((t) => (
                <tr key={t.id}>
                  <td>
                    {t.tradedAt.toLocaleDateString("en-IN", {
                      day: "numeric",
                      month: "short",
                      year: "numeric",
                    })}
                  </td>
                  <td>
                    <span className={`hd-side hd-side--${t.side}`}>{t.side}</span>
                  </td>
                  <td className="num">{t.quantity.toLocaleString("en-IN")}</td>
                  <td className="num">{inr(t.price)}</td>
                  <td className="num">{inr(t.price * t.quantity)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </article>
    </section>
  );
}
