export const ADVISOR_MODULES = [
  "Dashboard",
  "My Posts",
  "Comments",
  "Messages",
  "Subscribers",
  "Subscription Services",
  "Virtual Trading",
  "Courses",
  "Earnings",
  "Analytics",
  "Reports",
  "Notifications",
  "Profile",
] as const;

export const ADVISOR_MODULE_ROUTE_MAP: Record<string, string> = {
  Dashboard: "/advisor/dashboard",
  "My Posts": "/advisor/posts",
  Comments: "/advisor/comments",
  Messages: "/advisor/messages",
  Subscribers: "/advisor/subscribers",
  "Subscription Services": "/advisor/subscription-services",
  "Virtual Trading": "/advisor/paper",
  Courses: "/advisor/courses",
  Earnings: "/advisor/earnings",
  Analytics: "/advisor/analytics",
  Reports: "/advisor/reports",
  Notifications: "/advisor/notifications",
  Profile: "/advisor/profile",
};
